### ISSUE TITLE
Timestamping frames

### ISSUE THREAD

**Issue by glenne** [windows10luke/V4L2-to-NDI#10]
I would like to add a visible timestamp to every frame sent to NDI.  Can you provide general pointers on mods needed to this utility to achieve that?  If I can create the pixels to represent the timestamp, how would you suggest injecting them>

**Comment by lplassman** [comment]
Inside the process_image function is where you would want to inject your timestamp. You would have to replace the actual image frame pixels with the pixels from your timestamp in the frame buffer.

**Comment by glenne** [comment]
Thanks!  I will try that.  My current issue is my ndi stream to OBS is
stuttering.  I'm using an hdmi2csi input.  It runs for a second, stalls,
and then resumes.  Any tips for that?

G

**Comment by lplassman** [comment]
This could be any multitude of things, but I would suggest checking that the input frame rate and resolution into your hdmi2csi adapter match the given command line parameters. Also, it could be lack of power on the Raspberry Pi resulting in underclocking. I would check the network speed to ensure it is full gigabit between the Raspberry Pi and the machine running OBS. It could also be an issue with OBS - try the NDI Studio monitor application and see if the issue persists there.

**Comment by glenne** [comment]
Your guess was right on.  My source was not sending 1080p/30 like I thought and was more like 1080p/15.  Getting the properties dialed in allowed the video to operate nicely.
