### ISSUE TITLE
NDI-Stream is black.

### ISSUE THREAD

**Issue by EkiciLP** [windows10luke/V4L2-to-NDI#11]
Hello,

I'm using a raspberry-pi 4 2G (raspberrypios) and a Logitech Webcam and I'm trying to Stream its view over NDI to my PC. The problem is that when viewing the stream using the NDI Studio Monitor Tool I have no Image, it's just a black screen. when viewing the stream using the ffmpeg-ndi on the same pi it works. I've tried port forwarding but no luck... what else could the problem be?

**Comment by lplassman** [comment]
It typically is an issue with the firewall on a PC. Are you able to view any other NDI streams on the network with particular PC and network?

**Comment by philippkayser** [comment]
I have the same issue. Firewall is disabled.
I'm using this adapter
https://www.amazon.de/dp/B0BL3HVMWW?ref=ppx_yo2ov_dt_b_product_details&th=1

`
root@raspberrypi:/home/pi# v4l2ndi -d /dev/video0 -f -x 1920 -y 1080 -n 30000 -i -v Stream1 -c
Path: /dev/video0 Driver: uvcvideo
/dev/video0 support capture
/dev/video0 support streaming
Current pixel format: MJPG
Current frame width: 1920
Current frame height: 1080
Setting frame width to: 1920
Setting frame height to: 1080
Setting pixel format to: YUYV
Mapping /dev/video0 buffer 0, len 4147200
Mapping /dev/video0 buffer 1, len 4147200
Mapping /dev/video0 buffer 2, len 4147200
Mapping /dev/video0 buffer 3, len 4147200
Image Processing Threading Enabled
Current Queue Level 1
Queueing /dev/video0 buffer 0
Queueing /dev/video0 buffer 1
Queueing /dev/video0 buffer 2
Queueing /dev/video0 buffer 3
Starting stream into mmap buffer map, /dev/video0


`

**Comment by EkiciLP** [comment]
Hey,

For me the issue was not on the Transmitter side but on the receiver side. For some reason Windows and/or NDI Studio Monitor did not like me having multiple network adaptors so I had to disable all but the one with the NDI Stream. I also had to enable Media Streaming in the Network adaptor settings which for some reason gets disabled every restart.
