### ISSUE TITLE
Black output using webcam + OBS

### ISSUE THREAD

**Issue by pinpox** [windows10luke/V4L2-to-NDI#12]
Hello, I compiled the software and it starts correctly, but OBS (using the ndi plugins) shows only a black screen. 
This is the ouptupt of the program:
```
❯ result/bin/v4l2ndi -d /dev/video1                                             
Mapping /dev/video1 buffer 0, len 1843200
Mapping /dev/video1 buffer 1, len 1843200
Mapping /dev/video1 buffer 2, len 1843200
Mapping /dev/video1 buffer 3, len 1843200
Current Queue Level 1
Queueing /dev/video1 buffer 0
Queueing /dev/video1 buffer 1
Queueing /dev/video1 buffer 2
Queueing /dev/video1 buffer 3
Starting stream into mmap buffer map, /dev/video1
```

I can select the source in obs, but it is only black. Obs itself works correclty with other sources. 
Not sure if this is a bug or I'm doing something wrong, any idea what is going on?

**Comment by lplassman** [comment]
What device are you using to try to get a video stream from? It seems like it may not be able to read a frame from the device which is why the output is probably black. It could also be a device stream format error. Do you know what types of video frames (YUV2, MJPEG, etc.) your device supports as an output?

**Comment by pinpox** [comment]
I'm using my built-in notebook webcam to test with. How can I find out the frame type it supports?

I'll test using an external webcam aswell.

EDIT: Just tested again with an external usb webcam and have the same problem. Let me know what information I can provide to debug this.

**Comment by pinpox** [comment]
Found the problem: It seems webcams only work with `--yuyv` or `-f` for me.
